### ISSUE TITLE
Fenster der Asteroidenausbeute öffnet sich nicht

### ISSUE THREAD

**Issue by Antaiir** [kayahr/xadrian#14]
Ich verwende Xadrian 1.5.1. Seit kurzem habe ich das Problem, daß das Eingabefenster für die Ausbeute von Minen nicht mehr sichtbar ist. Es hat den Anschein, als würde sich ein "unsichtbares" Fenster öffnen, auf welchem der Fokus fixiert ist. Erst nach drücken von ESC läßt sich der Rechner wieder normal bedienen.

Ein Umweg ist für mich derzeit, Xadrian mit Adminrechten zu starten, wo dieses Problem _noch_ nicht auftritt. Der Fehler tritt auf 2 verschiedenen Rechnern auf.

Welche Infos werden noch von mir benötigt, um das Problem eingrenzen zu können?

VG
Antaiir

**Comment by kayahr** [comment]
Das Problem sagt mir auf Anhieb nichts, hab nicht mal eine Vermutung woran sowas liegen könnte. Nützliche Zusatzinfos wären:

1. Welches Betriebssystem? Windows 7? Windows 10? 32 oder 64 Bit?
2. Welche Java Version ist installiert? 32 oder 64 Bit?
3. Du schreibst, das Eingabefenster ist nicht sichtbar. Meinst du damit den gesamten Dialog? Geht der Dialog vielleicht UNTER dem Hauptfenster auf? So einen Mist macht Windows ja leider manchmal. Mal probiert in der Taskleiste Xadrian zu minimieren und wieder zu deminimieren?

**Comment by Antaiir** [comment]
Es ist mir furchtbar peinlich, aber das Problem lag tatsächlich an meiner Konfiguration. Xadrian ist definitiv unschuldig.

Ich verwende an meinen Rechnern mehrere Bildschirme, die jedoch nicht immer alle eingeschaltet sind. Normalerweise nutze ich nur den "Hauptschirm", die übrigen werden nur bei Bedarf zugeschaltet. Nun ist mir dieses Eingabefenster irgendwie mal auf einen der ausgeschalteten Bildschirme gerutscht, weswegen ich es nicht sehen konnte. 

Als mir etwas ähnliches mit einem anderen Programm passiert ist, welches für seine Abfrage ebenfalls ein neues Fenster öffnet, konnte ich noch sehen, wie der "Gummibandeffekt" von der Taskleiste in Richtung ausgeschaltetem Bildschirm öffnete. Daraufhin habe ich Xadrian nochmal getestet, während alle Bildschirme eingeschaltet waren, und siehe da, das Fenster war dort.

Ich entschuldige mich für die Umstände. Das war ganz klar mein eigener Fehler. Danke für Xadrian!

VG

**Comment by kayahr** [comment]
Kein Problem. :-)
