### ISSUE TITLE
No bombyx missile factory in xadrian

### ISSUE THREAD

**Issue by sywee34** [kayahr/xadrian#16]
I look in all the tabs, I find nowhere the missile factory bombyx, looking in all the yards I ended up finding one in the shipyard of: heart of legends.

**Comment by kayahr** [comment]
Bombyx factory? Heart of Legends? Which game are you playing? Do you have mods installed which add new sectors and factories? Xadrian only support the official sectors and factories.

**Comment by sywee34** [comment]
I play x3tc I have no add mod or anything just the official, bombyx factory that I found this finds at: legend's home

**Comment by kayahr** [comment]
Is "Bombyx" french? Xadrian isn't translated into French so I guess you use it in English. And if I found the right translation then you are looking for the Silkworm Missile Factory and this one is available in Legend's Home.

**Comment by kayahr** [comment]
Also see this forum post for a mapping from french names to english names:

http://forum.egosoft.com/viewtopic.php?t=243129

**Comment by sywee34** [comment]
Hoooo thanks :+1: thank you !

**Comment by kayahr** [comment]
You're welcome :)
