### ISSUE TITLE
Xadrian C++ Conversion

### ISSUE THREAD

**Issue by Darctalus** [kayahr/xadrian#18]
This not much of an issue as it is more of an interest.  I have been doing a personal project in C++ revolving around your software and I am attempting to reconstruct it in a completely different language. I am aware you have given the software for free and anything can be modified just as long as there were conditions. Though the conditions do not say anything about modifying it to another language with its on data structure. What is your policy for that? Thanks in advance.

**Comment by kayahr** [comment]
I don't have a real policy for that. Feel free to do what you want. Translate the Java Code you need to C++, use the XML files or convert them to whatever you need. I'm fine with that. Just don't use the name "Xadrian" in your project name. And it would be nice to get some credits in an About dialog for example. "Inspired by Xadrian", "Based on Xadrian" or something like that. With a link back to the Xadrian website.

Good luck for your project, looking forward to see the results. Hoping it is platform-independent and works on my Linux ;)

**Comment by Darctalus** [comment]
I am using Qt, a cross-platform. I am sure Linux should be able to run it just fine. One thing I did find curious is that I found no database in the build. Did you completely build the database with XML/Java properties only?

**Comment by kayahr** [comment]
Yes, all data is held in XML files. They are read once on application start and then I have everything in Java objects in memory. No need for SQL queries or stuff like that.

**Comment by Darctalus** [comment]
Do you have a proper control flow chart for your design or did you just do everything on the fly? If so, I'd like to see the chart for a reference. The sector map was quite clever. Did you do that with user interface grid layout and hover over labels?

**Comment by kayahr** [comment]
There is no flow chart, sorry.  And the [sector map](https://github.com/kayahr/xadrian/blob/master/src/main/java/de/ailis/xadrian/components/SectorSelector.java) is rendered completely manual with Graphics2D.

**Comment by Darctalus** [comment]
Ah, java based graphics. Hm, I don't think C++ can do that same them but perhaps I could find a proper graphics library.

**Comment by kayahr** [comment]
When you are already using Qt then [QPainter](http://doc.qt.io/qt-4.8/qpainter.html) is pretty much what Graphics2D is for Java.

**Comment by Darctalus** [comment]
I never used that in Qt. I will take a gander at it then. Thanks for the tip.
